version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: circleci/alpine:latest
    steps:
      - run: echo hello
  print_world:
    docker: 
      - image: circleci/alpine:latest
    steps:
      - run: echo world
workflows:
  welcome:
    jobs:
      - welcome/run
      - print hello
      - print world:
        requires: 
          - print_hello
