version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/alpine:latest
    steps:
      - run: echo hello
  print_world:
    docker: 
      - image: circleci/alpine:latest
    steps:
      - run: echo world
workflows:
  welcome:
    jobs:
      - welcome/run
      - print hello
      - print world:
        requires: 
          - print_hello
